http://localhost:4000/

###

http://localhost:4000/blocks

####
POST http://localhost:4000/blocks

{
    "message": "Data for my block"
}


###
http://localhost:4000/blocks/81f2ced897805e5539e750784e8d12bff104712be9bf8845ce52e006b0f3252e